#!/usr/bin/env zsh

source /home/fw05/.zshrc

echo "Launching Application, please wait!"

#terminator --new-tab -T "pm2" -e "zsh -c \"pm2 restart 1;exec zsh\"" &
#terminator --new-tab -T "roscore" -e "zsh -c \"source /home/fw/.zshrc;roscore;exec zsh\"" &
#terminator --new-tab -T "init" -e "zsh -c  \"source /home/fw/.zshrc;sleep 5s;roslaunch fw_rev_04_init fw_robot.launch;exec zsh\"" &
#terminator --new-tab -T "cam" -e "zsh -c \"source /home/fw/.zshrc;sleep 5s;roslaunch fw_rev_04_cam launch_d455_ekf_wheel_imu_jay.launch initial_reset:=false;exec zsh\"" &
#terminator --new-tab -T "slam" -e "zsh -c \"source /home/fw/.zshrc;sleep 5s;roslaunch fw_rev_04_rtabmap fw_navigation_stereo_test2_jay_2dlidar.launch rviz:=false database_path:=~/.ros/globalf4.db;exec zsh\"" &
#terminator --new-tab -T "nav" -e "zsh -c \"source /home/fw/.zshrc;sleep 5s;roslaunch fw_rev_04_navigation fw_move_base_teb.launch;exec zsh\"" &


gnome-terminal --geometry=1280x800 \
--tab --title="pm2" -e "zsh -c \"pm2 restart 1;exec zsh\"" \
--tab --title="docker_up" -e "zsh -c \"cd /home/fw05/docker_compose/docker_fw04; source /home/fw05/.zshrc; docker-compose up;exec zsh\""